### ISSUE TITLE
grafana_config resource no longer supports property restart_on_upgrade

### ISSUE THREAD

**Issue by hrak** [sous-chefs/chef-grafana#408]
## :ghost: Brief Description

Since v10.0.0 the `grafana_config` resource no longer seems to have the property `restart_on_upgrade`

## :pancakes: Cookbook version

v10.0.1

## :woman_cook:  Chef-Infra Version

17.6.18

## :tophat: Platform details

Ubuntu 20.04

## Steps To Reproduce

Use the following as [documented here](https://github.com/sous-chefs/grafana/blob/main/documentation/grafana_config.md)

```
grafana_config 'grafana' do
  owner 'grafana'
  group 'grafana'
  restart_on_upgrade true
end
```

result:

```
       ================================================================================
       Recipe Compile Error in /opt/kitchen/cache/cookbooks/lsw_grafana/recipes/default.rb
       ================================================================================

       NoMethodError
       -------------
       undefined method `restart_on_upgrade' for Custom resource grafana_config from cookbook grafana

       Cookbook Trace: (most recent call first)
       ----------------------------------------
         /opt/kitchen/cache/cookbooks/lsw_grafana/recipes/default.rb:20:in `block in from_file'
         /opt/kitchen/cache/cookbooks/lsw_grafana/recipes/default.rb:17:in `from_file'

       Relevant File Content:
       ----------------------
       /opt/kitchen/cache/cookbooks/lsw_grafana/recipes/default.rb:

        13:    subscribes :restart, ['template[/etc/grafana/grafana.ini]', 'template[/etc/grafana/ldap.toml]'], :delayed
        14:  end
        15:
        16:  # Configure grafana
        17:  grafana_config 'grafana' do
        18:    owner 'grafana'
        19:    group 'grafana'
        20>>   restart_on_upgrade true
        21:  end
        22:
        23:  grafana_config_server 'grafana' do
        24:    http_port node['lsw_grafana']['ini']['server']['http_port']
        25:    domain node['lsw_grafana']['ini']['server']['domain']
        26:    root_url node['lsw_grafana']['ini']['server']['root_url']
        27:  end
        28:
        29:  grafana_config_smtp 'grafana' do

       System Info:
       ------------
       chef_version=17.6.18
       platform=ubuntu
       platform_version=20.04
       ruby=ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
       program_name=/opt/chef/bin/chef-client
       executable=/opt/chef/bin/chef-client
```

**Comment by bmhughes** [comment]
As all resources now support `converge_if_changed` and will fire notifications, this has been replaced by either notifying a restart to a `grafana_service` resource or subscribing the service resource to the grafana configuration file being updated.
